blank_issues_enabled: true
contact_links:
  - name: Feature request (dnif / roadmap)
    url: https://github.com/dnif-backyard/roadmap/issues/new?template=feature_request.md
    about: Request a feature / enhancement
  - name: Bug report (dnif / roadmap)
    url: https://github.com/dnif-backyard/roadmap/issues/new?template=bug_report.md
    about: Report a bug